name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub's UI

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Use your Ruby version here
          bundler-cache: true

      - name: Check for Gemfile and rename if needed
        run: |
          if [ -f "gemfile" ] && [ ! -f "Gemfile" ]; then
            echo "Renaming gemfile to Gemfile for compatibility"
            mv gemfile Gemfile
          fi

      - name: Install dependencies
        run: bundle install

      - name: Install Node.js dependencies
        run: npm ci || npm install

      - name: Download fonts
        run: npm run download-fonts

      - name: Generate license images
        run: npm run generate-images

      - name: Build Jekyll site
        run: bundle exec jekyll build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages  # The branch where the built site will be deployed